type User {
  id: ID!
  email: String!
  username: String!
  bio: String
  avatar: String
  followers: [User]
  following: [User]
}

type AuthResponse {
  isOk: Boolean!
  token: String
  errors: [Error]
}

type ChangeInfoRespone {
  isOk: Boolean!
  user: User
  token: String
  errors: [Error]
}

type Query {
  getUser(query: String!): User!
  me: User!
}

type Mutation {
  register(username: String!, email: String!, password: String!): AuthResponse!
  login(email: String!, password: String!): AuthResponse!
  Togglefollow(userID: ID!): User!
  updateInfo(
    username: String!
    email: String!
    bio: String!
  ): ChangeInfoRespone!
  changePassword(
    currentPassword: String!
    newPassword: String!
    confirmPassword: String!
  ): ChangeInfoRespone!
}!
